# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Laundry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Laundry
  pod 'PromiseKit/Alamofire', '~> 6.0'


  target 'LaundryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LaundryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
